-- Blog Posts Table for Dystopia Fund
-- Tracks weekly blog post generation and publication

CREATE TABLE IF NOT EXISTS blog_posts (
  id SERIAL PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  title TEXT NOT NULL,
  filepath TEXT NOT NULL,
  weekly_return NUMERIC(5,2),
  content_preview TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for efficient date-based queries
CREATE INDEX IF NOT EXISTS idx_blog_posts_date ON blog_posts(date DESC);

-- Index for published_at queries
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(published_at DESC);

-- Comments for documentation
COMMENT ON TABLE blog_posts IS 'Weekly blog posts generated by workflow #5';
COMMENT ON COLUMN blog_posts.date IS 'Publication date (unique constraint ensures one post per day)';
COMMENT ON COLUMN blog_posts.title IS 'Blog post title (e.g., "Week in Dystopia: Oct 5-11, 2025")';
COMMENT ON COLUMN blog_posts.filepath IS 'Path in GitHub repo (e.g., "src/pages/blog/2025-10-11-week-in-dystopia.md")';
COMMENT ON COLUMN blog_posts.weekly_return IS 'Portfolio return percentage for that week';
COMMENT ON COLUMN blog_posts.content_preview IS 'First 200 chars of content (optional)';
COMMENT ON COLUMN blog_posts.published_at IS 'Timestamp when pushed to GitHub';
